package org.icrisat.gdms.upload.marker;


public enum UploadField {
	
	MarkerName("Marker-Name"),
	PrimerID("Primer-ID"),
	Alias("Alias"),
	Crop("Crop"),
	Genotype("Genotype"),
	Ploidy("Ploidy"),
	GID("GID"),
	PrincipleInvestigator("Principle-Investigator"),
	Contact("Contact"),
	Institute("Institute"),
	InchargePerson("Incharge-Person"),
	Repeat("Repeat"),
	NoOfRepeats("No-of-Repeats"),
	SSRType("SSR-Type"),
	MinAllele("Min-Allele"),
	MaxAllele("Max-Allele"),
	SSRNumber("SSR-Number"),
	SizeOfRepeatMotif("Size-of-Repeat-Motif"),
	AssayType("Assay-Type"),
	ForwardPrimer("Forward-Primer"),
	ReversePrimer("Reverse-Primer"),
	ProductSize("Product-Size"),
	ExpectedProductSize("Expected-Product-Size"),
	PrimerLength("Primer-Length"),
	ForwardPrimerTemperature("Forward-Primer-Temperature"),
	ReversePrimerTemperature("Reverse-Primer-Temperature"),
	FragmentSizeExpected("Fragment-Size-Expected"),
	FragmentSizeObserved("Fragment-Size-Observed"),
	Amplification("Amplification"),
	RestrictionEnzymeForAssay("Restriction-Enzyme-For-Assay"),
	PositionOnReferenceSequence("Position-On-Reference-Sequence"),
	Motif("Motif"),
	AnnealingTemperature("Annealing-Temperature"),
	ElongationTemperature("Elongation-Temperature"),
	Sequence("Sequence"),
	SequenceLength("Sequence-Length"),
	Reference("Reference"),
	Remarks("Remarks"), 
	MotifType("Motif-Type"),
	DatasetName("Dataset-Name"),
	DatasetDescription("Dataset-Description"),
	Genus("Genus"),
	Species("Species"),
	MissingData("Missing-Data"),
	Remark("Remark"),
	Accession("Accession"),
	Marker("Marker"),
	GelOrRun("Gel/Run"),
	Dye("Dye"),
	CalledAllele("Called-Allele"),
	RawData("Raw-Data"),
	Quality("Quality"),
	Height("Height"),
	Volume("Volume"),
	Amount("Amount"), 
	EmailContact("Email-Contact"),
	PopulationID("Population-ID"),
	ParentAGID("Parent-A-GID"), 
	ParentA("Parent-A"),
	ParentBGID("Parent-B-GID"),
	ParentB("Parent-B"), 
	PopulationSize("Population-Size"),
	PopulationType("Population-Type"),
	PurposeOfTheStudy("Purpose-Of-The-Study"),
	ScoringScheme("Scoring-Scheme"), 
	Line("Line"), 
	CreationDate("Creation-Date"),
	CloneID("Clone-ID"), 
	Q("Q"),
	Reproducibility("Reproducibility"),
	CallRate("Call-Rate"),
	PIC("PIC"),
	Discordance("Discordance"),
	GIDs("GIDs"),
	GermplasmName("Germplasm-Name"),
	Name("Name"),
	Chromosome("Chromosome"), 
	MapName("Map-Name"),
	Position("Position"),
	PosMin("Pos-Min"),
	PosMax("Pos-Max"),
	Trait("Trait"),
	Experiment("Experiment"),
	Clen("CLEN"),
	LFM("LFM"),
	RFM("RFM"),
	Effect("Effect"),
	additive("SE additive"),	
	HighParent("High value parent"),
	HighAllele("High value allele"),
	LowParent("Low value parent"),
	LowAllele("Low value allele"),
	LOD("LOD"),
	R2("R2"),
	Interactions("Interactions"),
	MapDescription("Map-Description"),
	MapUnit("Map-Unit"), 
	LinkageGroup("Linkage-Group"),
	PI("PI"),
	Email("E-mail"),
	REQUIRED("Req"),
	SNo("SNo"), 
	TraitID("Trait-ID"),
	Method("Method"), 
	Score("Score"),
	HighValueAllele("HighValueAllele"),
	ScoreValue("ScoreValue"),
	Assay("Assay"), 
	DNA("DNA"), 
	Plates("Plates"), 
	OrderNumber("Order-Number"), 
	ProjectNumber("Project-Number"), 
	GridVersion("Grid-Version"), 
	KBioSciencesGridReport("KBio-Sciences-Grid-Report")
	;
	
	private String strUploadField;
	
	private UploadField(String theUploadField){
		strUploadField = theUploadField;
	}
	
	public String toString(){
		return strUploadField;
	}

}
